# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
   desc "自动创建模块代码"
  lane :auto_create_code do
    sh("echo hello world")
    userName = sh("git config user.name")
    UI.message("用户名：#{userName}")
    moduleName = UI.input("请输入模块名称:")
    sh("python3 ../fastlane/fast.py #{moduleName} #{userName}")
  end
end
